In [1]:
import pickle
from sklearn.model_selection import train_test_split
import pandas as pd
df = pd.read_csv('customer_churn_dataset-testing-master.csv')

In [2]:
df.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0

In [3]:
df.columns

Index(['CustomerID', 'Age', 'Gender', 'Tenure', 'Usage Frequency',
       'Support Calls', 'Payment Delay', 'Subscription Type',
       'Contract Length', 'Total Spend', 'Last Interaction', 'Churn'],
      dtype='str')

In [4]:
df.drop('CustomerID', inplace=True ,axis=1)

In [5]:
df.head()

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,53,Female,58,24,9,2,Standard,Annual,533,18,0

In [6]:
df.isnull().sum()

Age                  0
Gender               0
Tenure               0
Usage Frequency      0
Support Calls        0
Payment Delay        0
Subscription Type    0
Contract Length      0
Total Spend          0
Last Interaction     0
Churn                0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df['Gender'].value_counts()

Gender
Female    34353
Male      30021
Name: count, dtype: int64

In [9]:
df['Contract Length'].value_counts()

Contract Length
Monthly      22130
Annual       21410
Quarterly    20834
Name: count, dtype: int64

In [10]:
df['Gender'] = df['Gender'].map({"Male":0,"Female":1})

In [11]:
df.head()

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,22,1,25,14,4,27,Basic,Monthly,598,9,1
1,41,1,28,28,7,13,Standard,Monthly,584,20,0
2,47,0,27,10,2,29,Premium,Annual,757,21,0
3,35,0,9,12,5,17,Premium,Quarterly,232,18,0
4,53,1,58,24,9,2,Standard,Annual,533,18,0

In [12]:
df['Contract Length'] = df['Contract Length'].map({"Monthly":0,"Annual":1,"Quarterly":2})

In [13]:
df['Subscription Type'] = df['Subscription Type'].map({"Basic":0,"Standard":1,"Premium":2})

In [14]:
df.head()

,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,22,1,25,14,4,27,0,0,598,9,1
1,41,1,28,28,7,13,1,0,584,20,0
2,47,0,27,10,2,29,2,1,757,21,0
3,35,0,9,12,5,17,2,2,232,18,0
4,53,1,58,24,9,2,1,1,533,18,0

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 64374 entries, 0 to 64373
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                64374 non-null  int64
 1   Gender             64374 non-null  int64
 2   Tenure             64374 non-null  int64
 3   Usage Frequency    64374 non-null  int64
 4   Support Calls      64374 non-null  int64
 5   Payment Delay      64374 non-null  int64
 6   Subscription Type  64374 non-null  int64
 7   Contract Length    64374 non-null  int64
 8   Total Spend        64374 non-null  int64
 9   Last Interaction   64374 non-null  int64
 10  Churn              64374 non-null  int64
dtypes: int64(11)
memory usage: 5.4 MB

In [16]:
x = df.drop('Churn',axis=1)
y = df['Churn']

In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2,random_state=42)

In [18]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
model = rf.fit(x_train,y_train)